blank_issues_enabled: true
contact_links:
  - name: Report to Panic
    url: "https://nova.app/help/?ext=(reported%20from%20https%3A%2F%2Fgithub.com%2Fapexskier%2Fnova-extension-utils%2Fissues%2Fnew)"
    about: Please report any hard crashes directly to Panic
